add phpcs to docksal

diff --git a/.docksal/commands/refresh b/.docksal/commands/refresh
--- a/.docksal/commands/refresh
+++ b/.docksal/commands/refresh
@@ -1,30 +1,33 @@
 #!/usr/bin/env bash
 
-#: exec_target = cli
-
-## Initialize stack and site (full reset)
+## Refresh DB
 ##
 ## Usage: fin refresh [environment id]
+## Defaults to the primary environment
 
-ENVIRONMENT=${1:-prod}
+# Abort if anything fails
+set -e
 
-cd /var/www/${DOCROOT}
+ENVIRONMENT=${1:-"$hostingenv"}
+DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
 
-DBFILE="/tmp/site.${ENVIRONMENT}.sql"
-if [ ! -f $DBFILE ] || [ ! -z $(find $DBFILE -mmin +60) ] ; then
+echo "Pulling Database..."
+fin pull db -y --hosting-env=${ENVIRONMENT}
 
-    if [ ! -f $DBFILE ]; then
-        echo "Database file does not exist."
-    elif [ ! -z $(find $DBFILE -mmin +60) ]; then
-        echo "Database file is older then 1 hours"
-    fi
+echo "Update code through composer"
+cd ${PROJECT_ROOT}
+composer install
 
-    echo "Exporting ${ENVIRONMENT} Database..."
-    drush @remote.${ENVIRONMENT} sql-dump > $DBFILE
-fi
+cd ${DOCROOT_PATH}
 
-echo "Truncating Database..."
-drush sql-drop -y
+echo "Clear cache"
+fin drush cr -y
 
-echo "Importing Database..."
-drush sql-cli < $DBFILE
+echo "Update Drupal DB"
+fin drush updatedb -y
+
+echo "Clear cache"
+fin drush cr -y
+
+echo "Login link"
+fin drush uli
